### ISSUE TITLE
How can I use it please?

### ISSUE THREAD

**Issue by Pancho111** [atask/interstice-cli#1]
Hi ,
how do I use this script?
I have a mac computer and I would like to record for example this station from shoutcast .
http://server-26.stream-server.nl:8706/stream
your response will be appreciated .
thank you

**Comment by atask** [comment]
Hello,
I've updated the main readme file with the command line options. In your case `interstice http://server-26.stream-server.nl:8706/stream` will start recording the station in the _recordings_ folder you run Interstice into.
